# Nombre de la aplicación
spring.application.name=medirecordatorio

# Configuración del puerto del servidor
server.port=8080

# Perfil activo de desarrollo (Semana 3)
spring.profiles.active=dev

# Nivel de logs para el paquete del proyecto (Semana 3)
logging.level.com.etitc.medirecordatorio=DEBUG

# Configuración del motor de plantillas Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# Codificación de la aplicación
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true